# Generated by Django 3.1.5 on 2021-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='description', max_length=130),
        ),
        migrations.AddField(
            model_name='listings',
            name='title',
            field=models.CharField(default='title', max_length=64),
        ),
    ]
